// Code generated by apigen from backend/openapi.json. DO NOT EDIT.

package depllo

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
)

// apigenTransport is the call behind every GeneratedAPI method: the SDK client sends it
// with its own sign-in and unwraps its own response envelope (a few hand-written lines
// in the client, apigenRequest). query is nil or the query string; body is nil (no body)
// or the JSON body. It returns the envelope's data, as JSON.
type apigenTransport interface {
	apigenRequest(ctx context.Context, method, path string, query url.Values, body map[string]any) (json.RawMessage, error)
}

// GeneratedAPI has all 45 feature routes of the Depllo API, one method each
// (generated from the API spec). A method takes the path parameters, then an *<Method>Args
// with the query fields (tagged query) and the JSON body fields (tagged json): required
// fields are plain values, optional ones pointers, slices or maps that nil leaves out,
// and Body passes the whole body. Each returns the response's data as JSON.
type GeneratedAPI struct{ c apigenTransport }

// Ptr returns a pointer to v, for the optional fields of the *Args structs.
func Ptr[T any](v T) *T { return &v }

// APIKeysCreateArgs are the inputs of GeneratedAPI.APIKeysCreate.
type APIKeysCreateArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// APIKeysCreate calls POST /api/v1/api-keys: Create an API key.
func (a *GeneratedAPI) APIKeysCreate(ctx context.Context, p *APIKeysCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &APIKeysCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("APIKeysCreate", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/api-keys", nil, payload)
}

// APIKeysDelete calls DELETE /api/v1/api-keys/{id}: Revoke an API key: requests with it get 401 from now on.
func (a *GeneratedAPI) APIKeysDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/api-keys/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// APIKeysList calls GET /api/v1/api-keys: List the workspace's active API keys (newest first).
func (a *GeneratedAPI) APIKeysList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/api-keys", nil, nil)
}

// AuditListArgs are the inputs of GeneratedAPI.AuditList.
type AuditListArgs struct {
	// Action is "action" in the query.
	Action any `query:"action"`

	// Actor is "actor" in the query.
	Actor any `query:"actor"`

	// Q is "q" in the query.
	Q any `query:"q"`
}

// AuditList calls GET /api/v1/audit: List audit.
func (a *GeneratedAPI) AuditList(ctx context.Context, p *AuditListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AuditListArgs{}
	}
	q := url.Values{}
	if p.Action != nil {
		q.Set("action", apigenQueryValue(p.Action))
	}
	if p.Actor != nil {
		q.Set("actor", apigenQueryValue(p.Actor))
	}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(p.Q))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/audit", q, nil)
}

// BillingCheckoutArgs are the inputs of GeneratedAPI.BillingCheckout.
type BillingCheckoutArgs struct {
	// Tier is "tier" in the body, required. One of: free, starter, growth, business.
	Tier string `json:"tier"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// BillingCheckout calls POST /api/v1/billing/checkout: POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl.
func (a *GeneratedAPI) BillingCheckout(ctx context.Context, p *BillingCheckoutArgs) (json.RawMessage, error) {
	if p == nil {
		p = &BillingCheckoutArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Tier != "" {
		payload["tier"] = p.Tier
	}
	if _, ok := payload["tier"]; !ok {
		return nil, apigenMissing("BillingCheckout", "Tier")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/billing/checkout", nil, payload)
}

// BillingList calls GET /api/v1/billing: Current subscription (free default) + the tier table.
func (a *GeneratedAPI) BillingList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing", nil, nil)
}

// CiLintArgs are the inputs of GeneratedAPI.CiLint.
type CiLintArgs struct {
	// ConfigText is "configText" in the body, required.
	ConfigText string `json:"configText"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// CiLint calls POST /api/v1/ci/lint: Create a lint.
func (a *GeneratedAPI) CiLint(ctx context.Context, p *CiLintArgs) (json.RawMessage, error) {
	if p == nil {
		p = &CiLintArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ConfigText != "" {
		payload["configText"] = p.ConfigText
	}
	if _, ok := payload["configText"]; !ok {
		return nil, apigenMissing("CiLint", "ConfigText")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/ci/lint", nil, payload)
}

// JobsArtifactsDownload calls GET /api/v1/jobs/{id}/artifacts/{artId}/download: List download.
func (a *GeneratedAPI) JobsArtifactsDownload(ctx context.Context, id string, artID string) (json.RawMessage, error) {
	path := "/api/v1/jobs/" + url.PathEscape(id) + "/artifacts/" + url.PathEscape(artID) + "/download"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// JobsCancel calls POST /api/v1/jobs/{id}/cancel: Cancel a job.
func (a *GeneratedAPI) JobsCancel(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/jobs/" + url.PathEscape(id) + "/cancel"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// JobsGet calls GET /api/v1/jobs/{id}: Get a job.
func (a *GeneratedAPI) JobsGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/jobs/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// JobsLogArgs are the inputs of GeneratedAPI.JobsLog.
type JobsLogArgs struct {
	// From is "from" in the query.
	From any `query:"from"`
}

// JobsLog calls GET /api/v1/jobs/{id}/log: List log.
func (a *GeneratedAPI) JobsLog(ctx context.Context, id string, p *JobsLogArgs) (json.RawMessage, error) {
	if p == nil {
		p = &JobsLogArgs{}
	}
	q := url.Values{}
	if p.From != nil {
		q.Set("from", apigenQueryValue(p.From))
	}
	path := "/api/v1/jobs/" + url.PathEscape(id) + "/log"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// JobsLogStreamArgs are the inputs of GeneratedAPI.JobsLogStream.
type JobsLogStreamArgs struct {
	// From is "from" in the query.
	From any `query:"from"`
}

// JobsLogStream calls GET /api/v1/jobs/{id}/log/stream: SSE tail: replays chunks from ?from= then polls the DB every ~1s.
func (a *GeneratedAPI) JobsLogStream(ctx context.Context, id string, p *JobsLogStreamArgs) (json.RawMessage, error) {
	if p == nil {
		p = &JobsLogStreamArgs{}
	}
	q := url.Values{}
	if p.From != nil {
		q.Set("from", apigenQueryValue(p.From))
	}
	path := "/api/v1/jobs/" + url.PathEscape(id) + "/log/stream"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// JobsPlay calls POST /api/v1/jobs/{id}/play: Play a job.
func (a *GeneratedAPI) JobsPlay(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/jobs/" + url.PathEscape(id) + "/play"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// JobsRetry calls POST /api/v1/jobs/{id}/retry: Retry a job.
func (a *GeneratedAPI) JobsRetry(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/jobs/" + url.PathEscape(id) + "/retry"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// PipelinesCancel calls POST /api/v1/pipelines/{id}/cancel: Cancel a pipeline.
func (a *GeneratedAPI) PipelinesCancel(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/pipelines/" + url.PathEscape(id) + "/cancel"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// PipelinesGet calls GET /api/v1/pipelines/{id}: Get a pipeline.
func (a *GeneratedAPI) PipelinesGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/pipelines/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PipelinesRetry calls POST /api/v1/pipelines/{id}/retry: Retry a pipeline.
func (a *GeneratedAPI) PipelinesRetry(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/pipelines/" + url.PathEscape(id) + "/retry"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// ProjectsConfig calls GET /api/v1/projects/{id}/config: List config.
func (a *GeneratedAPI) ProjectsConfig(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/config"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsCreateArgs are the inputs of GeneratedAPI.ProjectsCreate.
type ProjectsCreateArgs struct {
	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// RepoFullName is "repoFullName" in the body, required.
	RepoFullName string `json:"repoFullName"`

	// DefaultBranch is "defaultBranch" in the body.
	DefaultBranch *string `json:"defaultBranch,omitempty"`

	// ConfigPath is "configPath" in the body.
	ConfigPath *string `json:"configPath,omitempty"`

	// CloneToken is "cloneToken" in the body.
	CloneToken *string `json:"cloneToken,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreate calls POST /api/v1/projects: Create a project.
func (a *GeneratedAPI) ProjectsCreate(ctx context.Context, p *ProjectsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.RepoFullName != "" {
		payload["repoFullName"] = p.RepoFullName
	}
	if p.DefaultBranch != nil {
		payload["defaultBranch"] = *p.DefaultBranch
	}
	if p.ConfigPath != nil {
		payload["configPath"] = *p.ConfigPath
	}
	if p.CloneToken != nil {
		payload["cloneToken"] = *p.CloneToken
	}
	if _, ok := payload["repoFullName"]; !ok {
		return nil, apigenMissing("ProjectsCreate", "RepoFullName")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/projects", nil, payload)
}

// ProjectsCreatePipelinesArgs are the inputs of GeneratedAPI.ProjectsCreatePipelines.
type ProjectsCreatePipelinesArgs struct {
	// Ref is "ref" in the body, required.
	Ref string `json:"ref"`

	// Variables is "variables" in the body.
	Variables map[string]any `json:"variables,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreatePipelines calls POST /api/v1/projects/{id}/pipelines: Pipelines a project.
func (a *GeneratedAPI) ProjectsCreatePipelines(ctx context.Context, id string, p *ProjectsCreatePipelinesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreatePipelinesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Ref != "" {
		payload["ref"] = p.Ref
	}
	if p.Variables != nil {
		payload["variables"] = p.Variables
	}
	if _, ok := payload["ref"]; !ok {
		return nil, apigenMissing("ProjectsCreatePipelines", "Ref")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/pipelines"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProjectsCreateSchedulesArgs are the inputs of GeneratedAPI.ProjectsCreateSchedules.
type ProjectsCreateSchedulesArgs struct {
	// Cron is "cron" in the body, required.
	Cron string `json:"cron"`

	// Ref is "ref" in the body, required.
	Ref string `json:"ref"`

	// Active is "active" in the body.
	Active *bool `json:"active,omitempty"`

	// Variables is "variables" in the body.
	Variables map[string]any `json:"variables,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreateSchedules calls POST /api/v1/projects/{id}/schedules: Schedules a project.
func (a *GeneratedAPI) ProjectsCreateSchedules(ctx context.Context, id string, p *ProjectsCreateSchedulesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreateSchedulesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Cron != "" {
		payload["cron"] = p.Cron
	}
	if p.Ref != "" {
		payload["ref"] = p.Ref
	}
	if p.Active != nil {
		payload["active"] = *p.Active
	}
	if p.Variables != nil {
		payload["variables"] = p.Variables
	}
	if _, ok := payload["cron"]; !ok {
		return nil, apigenMissing("ProjectsCreateSchedules", "Cron")
	}
	if _, ok := payload["ref"]; !ok {
		return nil, apigenMissing("ProjectsCreateSchedules", "Ref")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/schedules"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProjectsCreateVariablesArgs are the inputs of GeneratedAPI.ProjectsCreateVariables.
type ProjectsCreateVariablesArgs struct {
	// Key is "key" in the body, required.
	Key string `json:"key"`

	// Value is "value" in the body, required.
	Value string `json:"value"`

	// Backend is "backend" in the body. One of: local, secronna.
	Backend *string `json:"backend,omitempty"`

	// Masked is "masked" in the body.
	Masked *bool `json:"masked,omitempty"`

	// Protected is "protected" in the body.
	Protected *bool `json:"protected,omitempty"`

	// FileType is "fileType" in the body.
	FileType *bool `json:"fileType,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreateVariables calls POST /api/v1/projects/{id}/variables: Variables a project.
func (a *GeneratedAPI) ProjectsCreateVariables(ctx context.Context, id string, p *ProjectsCreateVariablesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreateVariablesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Key != "" {
		payload["key"] = p.Key
	}
	if p.Value != "" {
		payload["value"] = p.Value
	}
	if p.Backend != nil {
		payload["backend"] = *p.Backend
	}
	if p.Masked != nil {
		payload["masked"] = *p.Masked
	}
	if p.Protected != nil {
		payload["protected"] = *p.Protected
	}
	if p.FileType != nil {
		payload["fileType"] = *p.FileType
	}
	if _, ok := payload["key"]; !ok {
		return nil, apigenMissing("ProjectsCreateVariables", "Key")
	}
	if _, ok := payload["value"]; !ok {
		return nil, apigenMissing("ProjectsCreateVariables", "Value")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/variables"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProjectsDelete calls DELETE /api/v1/projects/{id}: Delete a project.
func (a *GeneratedAPI) ProjectsDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// ProjectsDeleteSchedules calls DELETE /api/v1/projects/{id}/schedules/{schedId}: Delete a schedule.
func (a *GeneratedAPI) ProjectsDeleteSchedules(ctx context.Context, id string, schedID string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/schedules/" + url.PathEscape(schedID)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// ProjectsDeleteVariables calls DELETE /api/v1/projects/{id}/variables/{varId}: Delete a variable.
func (a *GeneratedAPI) ProjectsDeleteVariables(ctx context.Context, id string, varID string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/variables/" + url.PathEscape(varID)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// ProjectsGet calls GET /api/v1/projects/{id}: Get a project.
func (a *GeneratedAPI) ProjectsGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsGetPipelines calls GET /api/v1/projects/{id}/pipelines/{iid}: Get a pipeline.
func (a *GeneratedAPI) ProjectsGetPipelines(ctx context.Context, id string, iid string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/pipelines/" + url.PathEscape(iid)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsList calls GET /api/v1/projects: List projects.
func (a *GeneratedAPI) ProjectsList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/projects", nil, nil)
}

// ProjectsPipelinesArgs are the inputs of GeneratedAPI.ProjectsPipelines.
type ProjectsPipelinesArgs struct {
	// Q is "q" in the query.
	Q any `query:"q"`

	// Ref is "ref" in the query.
	Ref any `query:"ref"`

	// Source is "source" in the query.
	Source any `query:"source"`

	// Status is "status" in the query.
	Status any `query:"status"`
}

// ProjectsPipelines calls GET /api/v1/projects/{id}/pipelines: List pipelines.
func (a *GeneratedAPI) ProjectsPipelines(ctx context.Context, id string, p *ProjectsPipelinesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsPipelinesArgs{}
	}
	q := url.Values{}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(p.Q))
	}
	if p.Ref != nil {
		q.Set("ref", apigenQueryValue(p.Ref))
	}
	if p.Source != nil {
		q.Set("source", apigenQueryValue(p.Source))
	}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(p.Status))
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/pipelines"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ProjectsPipelinesCancel calls POST /api/v1/projects/{id}/pipelines/{iid}/cancel: Cancel a pipeline.
func (a *GeneratedAPI) ProjectsPipelinesCancel(ctx context.Context, id string, iid string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/pipelines/" + url.PathEscape(iid) + "/cancel"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// ProjectsPipelinesRetry calls POST /api/v1/projects/{id}/pipelines/{iid}/retry: Retry a pipeline.
func (a *GeneratedAPI) ProjectsPipelinesRetry(ctx context.Context, id string, iid string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/pipelines/" + url.PathEscape(iid) + "/retry"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// ProjectsSchedules calls GET /api/v1/projects/{id}/schedules: List schedules.
func (a *GeneratedAPI) ProjectsSchedules(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/schedules"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsSetConfigArgs are the inputs of GeneratedAPI.ProjectsSetConfig.
type ProjectsSetConfigArgs struct {
	// ConfigText is "configText" in the body, required.
	ConfigText string `json:"configText"`

	// CommitMessage is "commitMessage" in the body.
	CommitMessage *string `json:"commitMessage,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsSetConfig calls PUT /api/v1/projects/{id}/config: Config a project.
func (a *GeneratedAPI) ProjectsSetConfig(ctx context.Context, id string, p *ProjectsSetConfigArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsSetConfigArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ConfigText != "" {
		payload["configText"] = p.ConfigText
	}
	if p.CommitMessage != nil {
		payload["commitMessage"] = *p.CommitMessage
	}
	if _, ok := payload["configText"]; !ok {
		return nil, apigenMissing("ProjectsSetConfig", "ConfigText")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/config"
	return a.c.apigenRequest(ctx, "PUT", path, nil, payload)
}

// ProjectsUpdateSchedulesArgs are the inputs of GeneratedAPI.ProjectsUpdateSchedules.
type ProjectsUpdateSchedulesArgs struct {
	// Cron is "cron" in the body.
	Cron *string `json:"cron,omitempty"`

	// Ref is "ref" in the body.
	Ref *string `json:"ref,omitempty"`

	// Active is "active" in the body.
	Active *bool `json:"active,omitempty"`

	// Variables is "variables" in the body.
	Variables map[string]any `json:"variables,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsUpdateSchedules calls PATCH /api/v1/projects/{id}/schedules/{schedId}: Update a schedule.
func (a *GeneratedAPI) ProjectsUpdateSchedules(ctx context.Context, id string, schedID string, p *ProjectsUpdateSchedulesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsUpdateSchedulesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Cron != nil {
		payload["cron"] = *p.Cron
	}
	if p.Ref != nil {
		payload["ref"] = *p.Ref
	}
	if p.Active != nil {
		payload["active"] = *p.Active
	}
	if p.Variables != nil {
		payload["variables"] = p.Variables
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/schedules/" + url.PathEscape(schedID)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ProjectsUpdateVariablesArgs are the inputs of GeneratedAPI.ProjectsUpdateVariables.
type ProjectsUpdateVariablesArgs struct {
	// Value is "value" in the body.
	Value *string `json:"value,omitempty"`

	// Backend is "backend" in the body. One of: local, secronna.
	Backend *string `json:"backend,omitempty"`

	// Masked is "masked" in the body.
	Masked *bool `json:"masked,omitempty"`

	// Protected is "protected" in the body.
	Protected *bool `json:"protected,omitempty"`

	// FileType is "fileType" in the body.
	FileType *bool `json:"fileType,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsUpdateVariables calls PATCH /api/v1/projects/{id}/variables/{varId}: Update a variable.
func (a *GeneratedAPI) ProjectsUpdateVariables(ctx context.Context, id string, varID string, p *ProjectsUpdateVariablesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsUpdateVariablesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Value != nil {
		payload["value"] = *p.Value
	}
	if p.Backend != nil {
		payload["backend"] = *p.Backend
	}
	if p.Masked != nil {
		payload["masked"] = *p.Masked
	}
	if p.Protected != nil {
		payload["protected"] = *p.Protected
	}
	if p.FileType != nil {
		payload["fileType"] = *p.FileType
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/variables/" + url.PathEscape(varID)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ProjectsVariables calls GET /api/v1/projects/{id}/variables: List variables.
func (a *GeneratedAPI) ProjectsVariables(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/variables"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsWebhook calls POST /api/v1/projects/{id}/webhook: Idempotent webhook (re)create — the settings page "re-create" button.
func (a *GeneratedAPI) ProjectsWebhook(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/webhook"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// PublicBadgesPipelineSvg calls GET /api/v1/public/badges/{badgeToken}/pipeline.svg: List pipeline.svg.
func (a *GeneratedAPI) PublicBadgesPipelineSvg(ctx context.Context, badgeToken string) (json.RawMessage, error) {
	path := "/api/v1/public/badges/" + url.PathEscape(badgeToken) + "/pipeline.svg"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// RunnersList calls GET /api/v1/runners: List runners.
func (a *GeneratedAPI) RunnersList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/runners", nil, nil)
}

// RunnersPause calls POST /api/v1/runners/{id}/pause: Pause a runner.
func (a *GeneratedAPI) RunnersPause(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/runners/" + url.PathEscape(id) + "/pause"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// RunnersResume calls POST /api/v1/runners/{id}/resume: Resume a runner.
func (a *GeneratedAPI) RunnersResume(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/runners/" + url.PathEscape(id) + "/resume"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// SchedulesDelete calls DELETE /api/v1/schedules/{id}: Delete a schedule.
func (a *GeneratedAPI) SchedulesDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/schedules/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// SchedulesList calls GET /api/v1/schedules: List schedules.
func (a *GeneratedAPI) SchedulesList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/schedules", nil, nil)
}

// SchedulesUpdateArgs are the inputs of GeneratedAPI.SchedulesUpdate.
type SchedulesUpdateArgs struct {
	// Cron is "cron" in the body.
	Cron *string `json:"cron,omitempty"`

	// Ref is "ref" in the body.
	Ref *string `json:"ref,omitempty"`

	// Active is "active" in the body.
	Active *bool `json:"active,omitempty"`

	// Variables is "variables" in the body.
	Variables map[string]any `json:"variables,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// SchedulesUpdate calls PATCH /api/v1/schedules/{id}: Update a schedule.
func (a *GeneratedAPI) SchedulesUpdate(ctx context.Context, id string, p *SchedulesUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &SchedulesUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Cron != nil {
		payload["cron"] = *p.Cron
	}
	if p.Ref != nil {
		payload["ref"] = *p.Ref
	}
	if p.Active != nil {
		payload["active"] = *p.Active
	}
	if p.Variables != nil {
		payload["variables"] = p.Variables
	}
	path := "/api/v1/schedules/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// UsageList calls GET /api/v1/usage: List usage.
func (a *GeneratedAPI) UsageList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/usage", nil, nil)
}

// ProjectsPipelines2 is the old name of ProjectsGetPipelines (GET /api/v1/projects/{id}/pipelines/{iid}).
//
// Deprecated: use ProjectsGetPipelines.
func (a *GeneratedAPI) ProjectsPipelines2(ctx context.Context, id string, iid string) (json.RawMessage, error) {
	return a.ProjectsGetPipelines(ctx, id, iid)
}

// apigenBody copies Body, so the fields set over it never change the caller's map.
func apigenBody(body map[string]any) map[string]any {
	out := make(map[string]any, len(body))
	for k, v := range body {
		out[k] = v
	}
	return out
}

// apigenQueryValue writes a query value the way the server reads it: strings as they are,
// numbers and booleans as JSON writes them, anything else as JSON.
func apigenQueryValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return strconv.FormatBool(x)
	case int:
		return strconv.Itoa(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	}
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprint(v)
	}
	return string(b)
}

// apigenMissing is the error for a required body field that was neither set nor in Body.
func apigenMissing(method, field string) error {
	return fmt.Errorf("%s needs %s (or its key in Body)", method, field)
}
